filters/__init__.py
# -*- coding: UTF-8 -*-

views/cookies.py
# -*- coding: UTF-8 -*-
from flask import Flask, request, make_response, render_template, redirect, url_for, Blueprint

class Cookies:
    mod = Blueprint('cookies', __name__, url_prefix='/cookies')

    @mod.route('/')
    def index():
        return render_template("cookies/cookie.html")

    @mod.route('/getcookie/')
    def getcookie():
        username = request.cookies.get('username')
        return render_template("cookies/readcookie.html", username=username)

    @mod.route('/setcookie/', methods=['POST','GET'])
    def setcookie():
        if request.method == 'POST':
                username = request.form['username']
                #쿠키 초기화 오류 수정
                response = make_response(redirect(url_for('cookies.getcookie')))
                #response = make_response(render_template('readcookie.html')) #쿠키 저장후 바로 리다이렉트 처리 할때
                response.set_cookie('username', username)

                return response

views/fileUpload.py
# -*- coding: UTF-8 -*-
import os
from flask import Flask, request, render_template, redirect, Blueprint, make_response, url_for
from werkzeug.utils import secure_filename

root_path = ''
save_path = 'upload/'


class fileUpload:
    mod = Blueprint('fileUpload', __name__, url_prefix='/fileUpload')

    @mod.route('/')
    def index():
        return render_template('fileupload/index.html')

    @mod.route('/file_upload/', methods = ['POST'])
    def file_upload():

        if request.method == 'POST':
            f = request.files['file']
            f.save(os.path.join(root_path,save_path) + secure_filename(f.filename))
            filename = secure_filename(f.filename)

            response = make_response(render_template('fileupload/index.html', filename=filename))
            #response = make_response(redirect(url_for('fileUpload.index')))
            #response.headers['filename'] = filename

        return response

views/main.py
# -*- coding: UTF-8 -*-
from flask import  Flask, Blueprint, render_template


class Main:
    mod = Blueprint('main', __name__, )

    @mod.route('/')
    def index():
        return render_template('main.html')

views/sessions.py
# -*- coding: UTF-8 -*-
from flask import Flask, request, session, redirect, render_template, url_for, Blueprint, escape
from flask import flash


class Session:
    mod = Blueprint('sessions', __name__, url_prefix='/sessions')

    @mod.route('/')
    def index():
        #세션 유무 확인
        if 'username' in session:
            sessionName = session['username']
        else:
            sessionName = None

        return render_template('sessions/index.html', sessionName=sessionName)

    @mod.route('/login/', methods = ['POST'])
    def login():
        if request.method == 'POST':
            #세션 저장
            session['username'] = request.form['username']

        #플래싱
        flash('로그인 성공')

        return redirect(url_for('sessions.index'))

    @mod.route('/logout/')
    def logout():
        #세션 초기화
        session.pop('username',None)
        return redirect(url_for('sessions.index'))

templates/cookies/cookie.html
{% extends "layout.html" %}
{% block body %}
        <div>
            <label for="basic-url">쿠기 저장 테스트</label>
            <form action="{{ url_for('cookies.setcookie') }}" method="post" >
                <div class="input-group">
                    <span class="input-group-addon">쿠키명 : </span>
                    <input type="text" id="username" name="username" id="basic-url" aria-describedby="basic-addon3" class="form-control"/>
                </div>
                <br/>
                <button type="submit"class="btn btn-default">저장</button>
            </form>
        </div>
{% endblock %}

templates/cookies/readcookie.html
{% extends "layout.html" %}
{% block body %}
    <div class="panel panel-default">
        <div class="panel-body">
        입력한 쿠키 정보 : {{ username }}
        </div>
    </div>
{% endblock %}

templates/fileupload/index.html
{% extends "layout.html" %}
{% block body %}
        <div>
            <label for="basic-url">파일 업로드</label>
            <form action="{{ url_for('fileUpload.file_upload') }}" method="post" enctype="multipart/form-data">
                <div class="input-group">
                    <span class="input-group-addon">쿠키명 : </span>
                    <input type="file" id="file" name="file" id="basic-url" aria-describedby="basic-addon3" class="form-control"/>
                </div>
                <br/>
                <button type="submit"class="btn btn-default">저장</button>
            </form>
        </div>
        {% if filename %}
        <hr>
        <div>
            <label>업로드된 파일명 : {{ filename }}</label>
        </div>
        {%  endif %}
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
{#    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">#}
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">Flask Study</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="/">홈으로</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container" role="main">
        <br/><br/><br/><br/>
        {% block body %}{% endblock %}
    </div>
</body>
</html>

templates/main.html
{% extends "layout.html" %}
{% block body %}
        <div>
            <ul class="list-group">
                <li class="list-group-item">
                    <a href="{{ url_for('cookies.index') }}">쿠키 쓰기/읽기</a>
                </li>
                <li class="list-group-item">
                    <a href="{{ url_for('fileUpload.index') }}">파일 업로드</a>
                </li>
                <li class="list-group-item">
                    <a href="{{ url_for('sessions.index') }}">세션처리</a>
                </li>
            </ul>
        <div>
{% endblock %}

templates/show_entries.html
{% extends "layout.html" %}
{% block body %}
    {%  if session.logged_in %}

    {% endif %}
    <ul class="entries">
    {% for entry in entries %}
        <li><h2>{{ entry[0] }}</h2>{{ entry[1]|safe }}</li>
    {% else %}
        <li><em>Not Entries</em></li>
    {% endfor %}
    </ul>
{% endblock %}